# Site settings
name: Practice makes perfect
email: zhangyiss@icloud.com
author: Yi Zhang
url: https://yizhangcug.github.io
github: https://github.com/YiZhangCUG
baseurl: ''
description: Actually, practice makes better!
meta_description: Yi Zhang;Personal blog
motto: It's our wits that make us men.
banner: Learning without thinking makes confusion. Thinking without learning makes slack.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: YiZhangCUG

plugins: [jekyll-paginate]

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

